import '../styles/globals.scss';

import Footer from '@/layout/footer/footer';
import Header from '@/layout/header/header';
import { Host_Grotesk } from 'next/font/google';
import type { Metadata } from 'next';

const hostGrotesk = Host_Grotesk({
    subsets: ['latin'],
    weight: ['400', '500'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={hostGrotesk.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
